import base64
from pathlib import Path

scene_b64 = (
    "AAAAHGZ0eXBtcDQyAAAAAG1wNDFtcDQyaXNvbQAAAGxtdmhkAAAAANrPZRNAaAAAABAAAAAAAACo"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAA"
    "AAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAgAAABR0cmFrAAAAXHRraGQAAAAB2s9kQ2EAAAAQAAAAAA"
    "AACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAA"
    "AAEAAAAAAAAAAAAAAAAAAACAAAAAFN0dHMAAAAPc3R0cwAAAAEAAAABAAAAAQAAAAEAAAAAAAAAAQA"
    "AAAEAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAHNjYWwAAAAeY2FoZAAAAAHaz2RDYQAAA"
    "AMAAAAIAAAACgAAAAoAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAA"
    "AAAAAAAAAABAAAAAAAAAAAAAAAAAAAAgAAAABZbWluZgAAABR2bWhkAAAAANrPZEOkAAAAEAAAAAEA"
    "AABQAAAAACoAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAA"
    "AAEAAAAAAAAAAAAAAAAAAAAgAAAAI21kYXQAAADEAAAAAQwAZABIAEwAAABMYXZjNTkuNDEuMTAwAA"
    "ACAH//AAAAAAH//wAAAP//AAAAAP//AAAAAH//AAAAAP//AAAAAP//AAAAAH//AAAAAP//AAAAAP//AA"
    "AAAP//AAAAaG1ldGEAAAAAAAAAIWhkbHIAAAAAAAAAAG1kaXJhcHBsAAAAAAAAAAAAAAAAAAD//wAAA"
    "F9pbGRzAAAAFgAAAAUABgEIAAAACQAAAAEAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAB1tZGlhA"
    "AAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAVBkcmVmAAAAAAAAAAEAAAAMAAAAAQAAABAAAAABAAAAAA=="
)

confession_b64 = scene_b64  # reuse placeholder

media_dir = Path("media")
media_dir.mkdir(exist_ok=True)

def write_video(name: str, data_b64: str) -> None:
    data = base64.b64decode(data_b64)
    (media_dir / name).write_bytes(data)

write_video("scene.mp4", scene_b64)
write_video("confession.mp4", confession_b64)
print("Placeholder videos created.")
